# Generated by Django 6.0.1 on 2026-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('img_icon_url', models.URLField()),
                ('appid', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField()),
                ('final_formatted', models.CharField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
