from django.conf import settings
from django.utils import timezone

from .models import PlayerSummaryDTO, OwnedGamesDTO, GameInformation

import requests

steam_api_key = settings.STEAM_API_KEY
format = "json"

# TODO:
# 1. add support for https://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=steam_api_key&vanityurl={UsersCustomURL}
# 2. response looks as so: {"response":{"steamid":"76561198087999365","success":1}}
def get_steam_player_summary(steam_id64):
    """
    Returns a `PlayerSummaryDTO` object produced by the JSON response of ISteamUser/GetPlayerSummaries/v0002/.
    
    :param steam_id64: The 64 bit version of the user's steam id.
    """
    params = {
        'key': steam_api_key,
        'steamids': steam_id64,
        'format': format
    }

    response = requests.get('https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/', params)

    if response.status_code == requests.codes.ok:
        json_response = response.json()

        player_summary_dto = PlayerSummaryDTO.from_dict(json_response['response']['players'][0])

        return player_summary_dto
    else:
        return response.status_code
    
def get_steam_player_level(steam_id64):
    """
    Returns a an `int player_level` produced by the JSON response of IPlayerService/GetSteamLevel/v1/.
    
    :param steam_id64: The 64 bit version of the user's steam id.
    """
    params = {
        'key': steam_api_key,
        'steamid': steam_id64,
        'format': format
    }

    response = requests.get('http://api.steampowered.com/IPlayerService/GetSteamLevel/v1/', params)

    if response.status_code == requests.codes.ok:
        json_response = response.json()
        player_level = int(json_response['response']['player_level'])
        return player_level
    else:
        return response.status_code
    
def get_steam_user_owned_games(steam_id64):
    """
    Returns a list of `OwnedGamesDTO` objects produced by the JSON response from the Steam API call for IPlayerService/GetOwnedGames/v0001/.
    
    :param steam_id: The 64 bit version of the user's steam id.
    """
    params = {
        'key': steam_api_key,
        'steamid': steam_id64,
        'format': format,
        'include_appinfo': 1,
        'include_played_free_games': 1,
    }

    # Response = {"response":{}} if profile is private
    response = requests.get('https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/', params)

    if response.status_code == requests.codes.ok:
        json_response = response.json()

        # If user's profile is private, return empty
        if json_response == {"response": {}}:
            return {}

        owned_games_dtos = []
        
        for game in json_response['response']['games']:
            owned_games_dtos.append(OwnedGamesDTO.from_dict(game))

        owned_games_dtos.sort(reverse=True, key=sort_by_playtime)

        return owned_games_dtos
    else:
        return response.status_code


def sort_by_playtime(e: OwnedGamesDTO):
    return e.playtime_forever


# Possibly split this function into multiple code pieces
# Possibly also - delete DB and start again with the following ideals:
# 1. Check if game data exists in DB
# 2. If can't find the appid - then request it via the steam store
# 3. We need to add the following information:
# 4. Game name, Appid, Price, Currency, final_formatted, last_updated

# 5. This requires getting data from the OwnedGamesDTO:
# 6. appid, name, img_icon_url

# 7. And combining with the steamstore call:
# 8. price, currecny, final_formatted, last_updated <- locally done in the function i guess

# 9. If a game is free (find out how to find this), mark it in db as 'free'
# 9a. It looks like if a game is free, and we request steam store data, it returns the following:
# Example for marvel rivals: https://store.steampowered.com/api/appdetails?filters=price_overview&appids=2767030&cc=NZ
# {
#   "2767030": {
#     "success": true,
#     "data": []
#   }
# }
#
# Example for CS2: https://store.steampowered.com/api/appdetails?filters=price_overview&appids=730&cc=NZ
#{
#   "730": {
#     "success": true,
#     "data": []
#   }
# }
#
# Example for Muck: https://store.steampowered.com/api/appdetails?filters=price_overview&appids=1625450&cc=NZ
#{
#   "1625450": {
#     "success": true,
#     "data": []
#   }
# }

# 10. use 76561198190514485 for testing
def get_users_game_information_from_db(owned_games: OwnedGamesDTO):
    """
    Returns a list of GameInformation objects found in the DB.
    Will also create a GameInformation object if one doesn't exist for it in the DB.
    
    :param owned_games: List of `OwnedGamesDTO` objects generated by get_steam_user_owned_games
    """

    # ====================================================================
    # [ Check if any appid from owned_games does not already exist in DB ]
    # ====================================================================
    appids = [game.appid for game in owned_games]
    existing_game_info = GameInformation.objects.filter(appid__in=[appids])

    existing_appids = []
    for game_info in existing_game_info:
        existing_appids.append(game_info.appid)

    missing_appids = []
    for appid in appids:
        if appid not in existing_appids:
            missing_appids.append(appid)

    # ====================================================================
    # [ If missing_appids has data, then some games that the user has 
    #   are not in our DB. So we query the steam store API and store the
    #   data.]
    # ====================================================================
    if missing_appids:
        missing_owned_game_dtos = [game for game in owned_games if game.appid in missing_appids]
        for game in missing_owned_game_dtos:
            existing_game_info.append(_create_game_info_object_from_steam_store_api(game))

    print(f"Checking exisiting_game_info: {existing_game_info}")
    for obj in existing_game_info:
        print(obj)

    return existing_game_info


def _create_game_info_object_from_steam_store_api(owned_game_dto):
    """
    Creates and returns a GameInformation object, combining data from the `owned_game_dto` param and the data from the store.steampowered.com/api/ response.
    
    :param owned_game_dto: An `OwnedGamesDTO` object.
    """
    params = {
        'filters': 'price_overview',
        'appids': owned_game_dto.appid,
        'cc': 'NZ', # Only get $NZD requests
    }
    
    response = response = requests.get('https://store.steampowered.com/api/appdetails', params)

    # these defaults change if there's values to update from steam store API
    default_price = 0
    default_currency = "N/A"
    default_final_formatted = "N/A"

    if response.status_code == 200:
        json_data = response.json()
        price_info = json_data[f'{owned_game_dto.appid}']

        if 'success' in price_info and 'data' in price_info:
            price_data = price_info['data']
            if 'price_overview' in price_data:
                price_overview = price_data['price_overview']
                if price_overview:
                    default_price = price_overview['final'] * 0.01
                    default_currency = price_overview['currency']
                    default_final_formatted = price_overview['final_formatted']
            else:
                # if call was successful but there's no price_overview, 
                # then the game is free
                default_final_formatted = "FREE"

    game_info_obj = GameInformation (
        name=owned_game_dto.name,
        img_icon_url=owned_game_dto.img_icon_url,
        appid=owned_game_dto.appid,
        price=default_price,
        currency=default_currency,
        final_formatted=default_final_formatted,
        last_updated=timezone.now()
    )
    game_info_obj.save()

    return game_info_obj