from django.conf import settings
from django.utils import timezone
import logging

from .models import PlayerSummaryDTO, OwnedGamesDTO, GamePrice

import requests

steam_api_key = settings.STEAM_API_KEY
format = "json"

# TODO:
# 1. add support for https://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=steam_api_key&vanityurl={UsersCustomURL}
# 2. response looks as so: {"response":{"steamid":"76561198087999365","success":1}}
def get_steam_player_summary(steam_id64):
    """
    Returns a `PlayerSummaryDTO` object produced by the JSON response of ISteamUser/GetPlayerSummaries/v0002/.
    
    :param steam_id64: The 64 bit version of the user's steam id.
    """
    params = {
        'key': steam_api_key,
        'steamids': steam_id64,
        'format': format
    }

    response = requests.get('https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/', params)

    if response.status_code == requests.codes.ok:
        json_response = response.json()

        player_summary_dto = PlayerSummaryDTO.from_dict(json_response['response']['players'][0])

        return player_summary_dto
    else:
        return response.status_code
    
def get_steam_player_level(steam_id64):
    """
    Returns a an `int player_level` produced by the JSON response of IPlayerService/GetSteamLevel/v1/.
    
    :param steam_id64: The 64 bit version of the user's steam id.
    """
    params = {
        'key': steam_api_key,
        'steamid': steam_id64,
        'format': format
    }

    response = requests.get('http://api.steampowered.com/IPlayerService/GetSteamLevel/v1/', params)

    if response.status_code == requests.codes.ok:
        json_response = response.json()
        player_level = int(json_response['response']['player_level'])
        return player_level
    else:
        return response.status_code
    
def get_steam_user_owned_games(steam_id64):
    """
    Returns a list of `OwnedGamesDTO` objects produced by the JSON response from the Steam API call for IPlayerService/GetOwnedGames/v0001/.
    
    :param steam_id: The 64 bit version of the user's steam id.
    """
    params = {
        'key': steam_api_key,
        'steamid': steam_id64,
        'format': format,
        'include_appinfo': 1,
        'include_played_free_games': 1,
    }

    # Response = {"response":{}} if profile is private
    response = requests.get('https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/', params)

    if response.status_code == requests.codes.ok:
        json_response = response.json()

        # If user's profile is private, return empty
        if json_response == {"response": {}}:
            return {}

        owned_games_dtos = []
        
        for game in json_response['response']['games']:
            owned_games_dtos.append(OwnedGamesDTO.from_dict(game))

        owned_games_dtos.sort(reverse=True, key=sort_by_playtime)

        return owned_games_dtos
    else:
        return response.status_code


def sort_by_playtime(e: OwnedGamesDTO):
    return e.playtime_forever


# Possibly split this function into multiple code pieces
# Possibly also - delete DB and start again with the following ideals:
# 1. Check if game data exists in DB
# 2. If can't find the appid - then request it via the steam store
# 3. We need to add the following information:
# 4. Game name, Appid, Price, Currency, final_formatted, last_updated

# 5. This requires getting data from the OwnedGamesDTO:
# 6. appid, name, img_icon_url

# 7. And combining with the steamstore call:
# 8. price, currecny, final_formatted, last_updated <- locally done in the function i guess

# 9. If a game is free (find out how to find this), mark it in db as 'free'

# 10. use 76561198190514485 for testing

def get_players_owned_games_prices(appids):
    """
    Returns a list of GamePrice objects.
    Will also create a GamePrice object if one doesn't exist in the DB.
    
    :param appids: List of `OwnedGamesDTO.appid` generated by get_steam_user_owned_games
    """

    logger = logging.getLogger(__name__)
    existing_game_prices = GamePrice.objects.filter(appid__in=appids)
    logger.debug(f"Attempted to get list of existing game prices: {existing_game_prices}")

    game_prices_to_return = []

    existing_appids = []
    for obj in existing_game_prices:
        existing_appids.append(obj.appid)

        # also add to game_prices_to_return
        game_prices_to_return.append({
            'appid': obj.appid,
            'price': obj.price,
            'currency': obj.currency,
            'final_formatted': obj.final_formatted,
            'last_updated': obj.last_updated,
        })

    missing_appids = []
    for appid in appids:
        if appid not in existing_appids:
            missing_appids.append(appid)
    logger.info(f"May have created missing appids list: {missing_appids}")

    new_objects_to_save = []

    # query steam store API to retrieve them
    # so we don't get IP banned again #Based ✔️
    if missing_appids:
        for appid in missing_appids:
            # here, need to put cc = 'NZ' or something
            params = {
                'filters': 'price_overview',
                'appids': appid,
                'cc': 'NZ', # Only get $NZD requests
            }
            print("Testing, am I in the missing_apids function?")
            response = response = requests.get('https://store.steampowered.com/api/appdetails', params)

            # change these if there's values to update
            default_price = 0
            default_currency = "N/A"
            default_final_formatted = "N/A"

            if response.status_code == 200:
                json_data = response.json()
                
                price_info = json_data[f'{appid}']

                if 'success' in price_info and 'data' in price_info:
                    price_data = price_info['data']
                    if 'price_overview' in price_data:
                        price_overview = price_data['price_overview']
                        if price_overview:
                            default_price = price_overview['final'] * 0.01
                            default_currency = price_overview['currency']
                            default_final_formatted = price_overview['final_formatted']

            new_objects_to_save.append(GamePrice (
                appid=appid,
                price=default_price,
                currency=default_currency,
                final_formatted=default_final_formatted,
                last_updated=timezone.now()
            ))
    
    if new_objects_to_save:
        GamePrice.objects.bulk_create(new_objects_to_save)
        for obj in new_objects_to_save:
            game_prices_to_return.append({
                'appid': obj.appid,
                'price': obj.price,
                'currency': obj.currency,
                'final_formatted': obj.final_formatted,
                'last_updated': obj.last_updated,
            })

    return game_prices_to_return